#ifndef __RENDER_SHADER_DEF_H__
#define __RENDER_SHADER_DEF_H__

#include <cstdint>

namespace Pionner
{
	enum ShaderType : uint8_t
	{
		SHADER_TYPE_MESH,
		SHADER_TYPE_LIGHTED_MESH,
		SHADER_TYPE_SHADOW_MAP,
		SHADER_TYPE_DEPTH_SCREEN_2D,
		SHADER_TYPE_INFINITE_GRID,
		SHADER_TYPE_CIRCLE,
		SHADER_TYPE_COLOR_GEOMETRY,
		SHADER_TYPE_CNT
	};
}

#endif